=== joe-lynch/ODPE/Linux/description.dtd
<!-- Document type definition for describing inference systems to GraPE.
     (C) 2006 Max Schaefer, licensed under the GPL (see COPYING) -->

<!ELEMENT system (normal, subatomic, backend)>
<!ATTLIST system	name CDATA #REQUIRED
					subatomic-name CDATA #REQUIRED>

<!ELEMENT normal (syntax, rules)>
<!ELEMENT subatomic (syntax, rules)>

<!ELEMENT syntax (binary-infix|binary-outfix|unary-outfix|unary-prefix|unary-postfix|constant|constants|name|embed)*>

<!ELEMENT binary-infix   EMPTY>
<!ATTLIST binary-infix   id        CDATA #IMPLIED
                         symbol    CDATA #REQUIRED
                         input     CDATA #IMPLIED
						 tex       CDATA #IMPLIED
					     prec      CDATA #IMPLIED
						 assoc     (yes|no) "yes"
						 comm      (yes|no) "yes"
						 leftprec  CDATA #IMPLIED
						 leftop    CDATA "singleton"
						 rightprec CDATA #IMPLIED
						 rightop   CDATA "singleton">

<!ELEMENT binary-outfix  EMPTY>
<!ATTLIST binary-outfix  id        CDATA #IMPLIED
                         symbol    CDATA #IMPLIED
						 startsym  CDATA #IMPLIED
						 sepsym    CDATA #IMPLIED
						 endsym    CDATA #IMPLIED
                         input     CDATA #IMPLIED
						 instart   CDATA #IMPLIED
						 insep     CDATA #IMPLIED
						 inend     CDATA #IMPLIED
						 tex       CDATA #IMPLIED
						 texstart  CDATA #IMPLIED
						 texsep    CDATA #IMPLIED
						 texend    CDATA #IMPLIED
						 prec      CDATA #IMPLIED
						 assoc     (yes|no) "yes"
						 comm      (yes|no) "yes"
						 leftprec  CDATA #IMPLIED
						 leftop    CDATA "singleton"
						 rightprec CDATA #IMPLIED
						 rightop   CDATA "singleton">

<!ELEMENT unary-outfix   EMPTY>
<!ATTLIST unary-outfix   id        CDATA #IMPLIED
                         symbol    CDATA #IMPLIED
						 startsym  CDATA #IMPLIED
						 endsym    CDATA #IMPLIED
                         input     CDATA #IMPLIED
						 instart   CDATA #IMPLIED
						 inend     CDATA #IMPLIED
						 tex       CDATA #IMPLIED
						 texstart  CDATA #IMPLIED
						 texend    CDATA #IMPLIED
						 prec      CDATA #IMPLIED
						 opprec    CDATA #IMPLIED
						 op        CDATA "singleton"
						 grouping  (yes|no) "no">

<!ELEMENT unary-prefix   EMPTY>
<!ATTLIST unary-prefix   id        CDATA #IMPLIED
                         symbol    CDATA #REQUIRED
                         input     CDATA #IMPLIED
						 tex       CDATA #IMPLIED
						 prec      CDATA #IMPLIED
						 opprec    CDATA #IMPLIED
						 op        CDATA "singleton">

<!ELEMENT unary-postfix  EMPTY>
<!ATTLIST unary-postfix  id        CDATA #IMPLIED
                         symbol    CDATA #REQUIRED
                         input     CDATA #IMPLIED
						 tex       CDATA #IMPLIED
						 prec      CDATA #IMPLIED
						 opprec    CDATA #IMPLIED
						 op        CDATA "singleton">

<!ELEMENT constant       EMPTY>
<!ATTLIST constant       id        CDATA #IMPLIED
                         symbol    CDATA #REQUIRED
                         input     CDATA #IMPLIED
						 tex       CDATA #IMPLIED
						 prec      CDATA #IMPLIED>

<!ELEMENT constants      EMPTY>
<!ATTLIST constants      ids       NMTOKENS #IMPLIED
						 symbols   NMTOKENS #REQUIRED
						 inputs    NMTOKENS #IMPLIED
						 texs      NMTOKENS #IMPLIED
						 prec      CDATA    #IMPLIED>
			 
<!ELEMENT name           EMPTY>
<!ATTLIST name           prec   CDATA #IMPLIED>

<!ELEMENT embed          EMPTY>
<!ATTLIST embed          context CDATA #REQUIRED>

<!ELEMENT rules (inference-rule|reverse-inference-rule|transformation-rule)*>

<!ELEMENT inference-rule EMPTY>
<!ATTLIST inference-rule id   CDATA #IMPLIED
					     name CDATA #REQUIRED
                         tex  CDATA #IMPLIED
			             enabled (yes|no) "yes">
							  
<!ELEMENT reverse-inference-rule EMPTY>
<!ATTLIST reverse-inference-rule id   CDATA #IMPLIED
								 name CDATA #REQUIRED
								 tex  CDATA #IMPLIED
								 enabled (yes|no) "yes">

<!ELEMENT backend ANY>
<!ATTLIST backend class CDATA #REQUIRED>

<!ENTITY leftPoint "&#x3c;">
<!ENTITY leftTriangle "&#x25C1;"> 
<!ENTITY circledTimes "&#8855;">
<!ENTITY unfilledBullet "&#9675;">
<!ENTITY neg   "&#x00AC;">
<!ENTITY vel   "&#x2228;">
<!ENTITY wedge "&#x2227;">
<!ENTITY vdash "&#x22A2;">
<!ENTITY bot   "&#x22A5;">
<!ENTITY top   "&#x22A4;">
<!ENTITY Leftarrow "&#x21D0;">
<!ENTITY Uparrow "&#x21D1;">
<!ENTITY Rightarrow "&#x21D2;">
<!ENTITY Downarrow "&#x21D3;">
<!ENTITY LeftRightarrow "&#x21D4;">
<!ENTITY leftarrow "&#x2190;">
<!ENTITY uparrow "&#x2191;">
<!ENTITY rightarrow "&#x2192;">
<!ENTITY downarrow "&#x2193;">
<!ENTITY leftrightarrow "&#x2194;">
<!ENTITY emptyset "&#x2205;">
<!ENTITY horseshoe "&#x2283;">
<!ENTITY amp "&#38;">
<!ENTITY blackstar "&#x2605;">
<!ENTITY blackstaroverline "&#773;&#x2605;">
<!ENTITY zero "&#x2080;">
<!ENTITY one "&#x2081;">
<!ENTITY two "&#x2082;">
<!ENTITY three "&#x2083;">
<!ENTITY four "&#x2084;">
<!ENTITY five "&#x2085;">
<!ENTITY six "&#x2086;">
<!ENTITY seven "&#x2087;">
<!ENTITY eight "&#x2088;">
<!ENTITY nine "&#x2089;">
<!ENTITY macron "&#x304;">
<!ENTITY phi "&#x03D5;">

=== joe-lynch/ODPE/skv-maude.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE system SYSTEM "description.dtd" [
    <!ENTITY % odpe2maude SYSTEM "odpe2maude.dtd">
    %odpe2maude;
]>
<system name="SKV">
  <syntax>
    <unary-prefix  symbol="-" tex="\overline{#1}"/>
    <unary-prefix  symbol="&blackstar;" input="*"/>
    <binary-outfix id="par" symbol="(⅋)" input="[,]"/>
    <binary-outfix id="tensor" symbol="(&circledTimes;)" input="(,)"/>
    <binary-outfix id="seqcon" symbol="(&leftTriangle;)" input="&lt;;&gt;" comm="no"/>
    <constant      symbol="&unfilledBullet;" input="o"/>
    <constants     symbols="a b c d e f g h i j"/>
    <constant      symbol="a&one;"   input="a1"/>
    <constant      symbol="a&two;"   input="a2"/>
    <constant      symbol="a&three;" input="a3"/>
    <constant      symbol="a&four;"  input="a4"/>
    <constant      symbol="b&one;"   input="b1"/>
    <constant      symbol="b&two;"   input="b2"/>
    <constant      symbol="b&three;" input="b3"/>
    <constant      symbol="b&four;"  input="b4"/>
    <constant      symbol="c&one;"   input="c1"/>
    <constant      symbol="c&two;"   input="c2"/>
    <constant      symbol="c&three;" input="c3"/>
    <constant      symbol="c&four;"  input="c4"/>
    <constant      symbol="d&one;"   input="d1"/>
    <constant      symbol="d&two;"   input="d2"/>
    <constant      symbol="d&three;" input="d3"/>
    <constant      symbol="d&four;"  input="d4"/>
    <constant      symbol="e&one;"   input="e1"/>
    <constant      symbol="e&two;"   input="e2"/>
    <constant      symbol="e&three;" input="e3"/>
    <constant      symbol="e&four;"  input="e4"/>
    <constant      symbol="f&one;"   input="f1"/>
    <constant      symbol="f&two;"   input="f2"/>
    <constant      symbol="f&three;" input="f3"/>
    <constant      symbol="f&four;"  input="f4"/>
    <constant      symbol="g&one;"   input="g1"/>
    <constant      symbol="g&two;"   input="g2"/>
    <constant      symbol="g&three;" input="g3"/>
    <constant      symbol="g&four;"  input="g4"/>
    <constant      symbol="e&one;"   input="h1"/>
    <constant      symbol="e&two;"   input="h2"/>
    <constant      symbol="e&three;" input="h3"/>
    <constant      symbol="e&four;"  input="h4"/>
    
     
  </syntax>
  <rules>
    <inference-rule id="identity"  name="i"/>
    <inference-rule id="cut" name="ī"/>
    <inference-rule id="switch" name="s"/> 
    <inference-rule id="seq" name="q"/>
    <inference-rule id="coseq" name="q̄"/>
    <inference-rule id="star" name="&blackstar;" />
    <inference-rule id="costar" name="&blackstaroverline;" />
    <inference-rule id="promotion" name="p"/>
    <inference-rule id="copromotion" name="p̄"/>
    <inference-rule id="contraction" name="c"/>
    <inference-rule id="cocontraction" name="c̄"/>
  </rules>
  <backend class="odpe.backend.odpe2maude.ODPE2Maude">
    <load name="nnf_SKV.maude"/>
    <load name="skv.maude"/>
    <inferencer name="SKV-Meta"/>
    <normalizer name="NNF"/>
    <maudename id="par" name="[_,_]"/>
    <maudename id="tensor" name="{_,_}"/>
    <maudename id="seqcon" name="&lt;_;_&gt;"/>
    <result-sort name="Structure"/>
  </backend>
</system>

=== joe-lynch/ODPE/MacOS/ksg-maude.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE system SYSTEM "description.dtd" [
    <!ENTITY % odpe2maude SYSTEM "odpe2maude.dtd">
    %odpe2maude;
]>

<system name="KSg" subatomic-name="SAM">
    <normal>
        <syntax>
            <unary-prefix  symbol="-" input="-"/>
            <binary-outfix id="dis" symbol="[&vel;]" input="[,]"/>
            <binary-outfix id="copar" symbol="(&wedge;)" input="(,)"/>
            <constant      symbol="tt"/>
            <constant      symbol="ff"/>
            <constant      symbol="t"/>
            <constants     symbols="a b c d e f g h i j"/>
            <constant      symbol="a&one;"   input="a1"/>
            <constant symbol="&phi;&one;" input="phi1"/>
            <constant symbol="&phi;&two;" input="phi2"/>
            <constant symbol="&phi;&three;" input="phi3"/>
            <constant symbol="&phi;&four;" input="phi4"/>
            <constant symbol="&phi;&five;" input="phi5"/>
            <constant symbol="&phi;&six;" input="phi6"/>
            <constant symbol="&phi;&seven;" input="phi7"/>
            <constant symbol="&phi;&eight;" input="phi8"/>
            <constant symbol="&phi;&nine;" input="phi9"/>
            <constant symbol="&phi;&one;&zero;" input="phi10"/>
            <constant symbol="&phi;&one;&one;" input="phi11"/>
            <constant symbol="&phi;&one;&two;" input="phi12"/>
            <constant symbol="&phi;&one;&three;" input="phi13"/>
            <constant symbol="&phi;&one;&four;" input="phi14"/>
            <constant symbol="&phi;&one;&five;" input="phi15"/>
            <constant symbol="&phi;&one;&six;" input="phi16"/>


        </syntax>
          
        <rules>
            <inference-rule id="i_down"  name="i&downarrow;"/>
            <inference-rule              name="s"/> 
            <inference-rule id="w_down"  name="w&downarrow;"/>
            <inference-rule id="c_down"  name="c&downarrow;"/>
            <inference-rule id="c_up"    name="c&uparrow;"/>
            <inference-rule              name="tt-dis" />
            <inference-rule              name="ff-con"/>
            <inference-rule              name="tt-elim"/>
            <inference-rule id="equality" name="="/>
            <inference-rule id="nowt" name=" "/>

            <reverse-inference-rule id="i-up-r"  name="i&uparrow;"/>
            <reverse-inference-rule id="s-r"     name="s"/>
            <reverse-inference-rule id="w-up-r"  name="w&uparrow;"/>
            <reverse-inference-rule id="c-up-r"  name="c&uparrow;"/>
            <reverse-inference-rule id="c-down-r"    name="c&downarrow;"/>  
        </rules>
    </normal>
     
    <subatomic>
        <syntax>
            <constant      symbol="ff"/>
            <constant      symbol="tt"/>
        </syntax>
          
        <rules>
            <inference-rule id="eq" name="="/>
            <inference-rule id="a_down" name="a&downarrow;"/>
            <inference-rule id="a_up" name="a&uparrow;"/>
            <inference-rule id="conj_down" name="&wedge;&downarrow;"/>
            <inference-rule id="disj_up" name="&vel;&uparrow;"/>
            <inference-rule id="m" name="m"/>
            <inference-rule id="ac" name="ac"/>
            <inference-rule id="acc" name="acc"/>
            <inference-rule id="c_down" name="c&downarrow;"/>
            <inference-rule id="c_up" name="c&uparrow;"/>
                
            <reverse-inference-rule id="eq-r" name="="/>
            <reverse-inference-rule id="a-down-r" name="a&downarrow;"/>
            <reverse-inference-rule id="a-up-r" name="a&uparrow;"/>
            <reverse-inference-rule id="conj-down-r" name="&wedge;&downarrow;"/>
            <reverse-inference-rule id="disj-up-r" name="&vel;&uparrow;"/>
            <reverse-inference-rule id="m-r" name="m"/>
            <reverse-inference-rule id="ac-r" name="ac"/>
            <reverse-inference-rule id="acc-r" name="acc"/>
            <reverse-inference-rule id="c-down-r" name="c&downarrow;"/>
            <reverse-inference-rule id="c-up-r" name="c&uparrow;"/>
        </rules>
    </subatomic>
  
    <backend class="odpe.backend.odpe2maude.ODPE2Maude">
        <load name="sam.maude"/>
        <load name="s.maude"/>
        <load name="strat.maude"/>
        <load name="ksg.maude"/>
        <inferencer name="KSg-Meta"/>
        <reverseinferencer name="KSg-Meta-Reverse"/>
        <sa_inferencer name="SAM-Meta"/>
        <sa_reverseinferencer name="SAM-Meta-Reverse"/>
        <normalizer name="NNF"/>
        <subatomiser name="SAM-Meta"/>
        <interpreter name="S-INT"/>
        <maudename id="dis" name="[_,_]"/>
        <maudename id="copar" name="{_,_}"/>
        <result-sort name="Structure"/>
    </backend>


</system>
